spring:
  profiles:
    # 指定生效的的文件
    active: dev
# spring actuator 提供了对项目的监控功能,参考：https://www.cnblogs.com/ming-blogs/p/10697033.html
management:
  endpoints:
    web:
      exposure:
        include: '*'
